name = "my-backend"
main = "src/index.ts"
compatibility_date = "2023-07-24"



[[d1_databases]]
binding = "DB"
database_name = "my-guestbook-db"
database_id = "86e92860-08ef-4e6d-9513-e6ed5a9e04b3"


